Refactor repository to make pip installable gear package.
flywheel-apps/dcm2niix pull request #7
Opened 2021-02-04 23:18 UTC by margaretmahan

2021-02-04 23:59 UTC, NPann requested changes
LGTM. Just the few minors comments below in prep for the migration to gitlab.

2021-02-04 23:59 UTC, NPann commented on setup.py
> +VERSION = "1.2.2_1.0.20201102"
What about parsing it from the manifest.json directly to avoid human error?

2021-02-04 23:59 UTC, NPann commented on setup.py
> +    name="dcm2niix-gear",
Would rename as "fw-gear-dcm2niix". In gitlab that's how we have started enforcing this. The idea being to group all gear related packages under a common prefix.

2021-02-05 02:28 UTC, NPann approved these changes

2021-02-05 15:38 UTC, qian587 approved these changes
Looks good to me too!

2021-02-05 21:51 UTC, merged